### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zillerium** [poanetwork/poa-bridge-contracts#113] opened 2018-11-30 11:51 UTC
I am trying to follow the README file. It states run sudo npm install but this fails for me.

I have Ubuntu 18.04. npm is 6.4.1. node 10/14.1. I even tried running as root and I had the same error. I took a got clone and then I tried the sudo npm install.

What should I do to solve this?

trevor@bridge2:~/bridge/poa-bridge-contracts$ sudo npm install

> sha3@1.2.0 install /home/trevor/bridge/poa-bridge-contracts/node_modules/sha3
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/trevor/bridge/poa-bridge-contracts/node_modules/sha3/build'
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/trevor/bridge/poa-bridge-contracts/node_modules/sha3
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN webpack-cli@2.0.13 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN poa-parity-bridge-contracts@1.0.0 No repository field.
npm WARN poa-parity-bridge-contracts@1.0.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trevor/.npm/_logs/2018-11-30T11_47_26_568Z-debug.log

**Comment by akolotov** [comment] 2018-11-30 12:12
You are in `master` branch, right? Could you attach entire log?

BTW, you could try to use the docker to deploy contracts. Just follow instructions: https://github.com/poanetwork/poa-bridge-contracts#deployment-in-the-docker-environment

**Comment by patitonar** [comment] 2018-11-30 12:20
The issue is related to node 10. Please try using node 8. It seems that some dependencies need to be updated in order to work correctly with this version.  Also I think we need to add `.nvmrc` file on root folder too.

**Comment by zillerium** [comment] 2018-11-30 15:34
> You are in `master` branch, right? Could you attach entire log?
> 
> BTW, you could try to use the docker to deploy contracts. Just follow instructions: https://github.com/poanetwork/poa-bridge-contracts#deployment-in-the-docker-environment

Docker works with this. Any idea about this error. I have a private network running 3 nodes. I want to basically do heavy computation on the private network and then access/update ether balances on Ropsten. 

 Invalid environment variables:
    HOME_OWNER_MULTISIG: Invalid address: 0x
    HOME_UPGRADEABLE_ADMIN_VALIDATORS: Invalid address: 0x
    HOME_UPGRADEABLE_ADMIN_BRIDGE: Invalid address: 0x
    FOREIGN_OWNER_MULTISIG: Invalid address: 0x
    FOREIGN_UPGRADEABLE_ADMIN_VALIDATORS: Invalid address: 0x
    FOREIGN_UPGRADEABLE_ADMIN_BRIDGE: Invalid address: 0x
    VALIDATORS: Invalid address: "0x
    ERC20_TOKEN_ADDRESS: Invalid address: 
    BRIDGEABLE_TOKEN_DECIMALS: Invalid number input: ""18""

 Exiting with error code 1

**Comment by akolotov** [comment] 2018-12-11 20:13
Sorry for late response. The validator address must be without quotes.

**Comment by akolotov** [comment] 2019-02-18 19:31
The issue with old version of node.js addressed by #154 in the `develop` branch. @zillerium please check.

**Closed** 2019-05-22 22:13 UTC
Labels: review
